#!/bin/bash
#Build Configuration & Enviroment Variable (Change the values depending on your System)
defconfig=bcm2711_defconfig
KERNEL=kernel7l

# Installs and Downloads functions and scripts (Dependencies and Github files)
sh performance_monitor1 & sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make -y
git clone git@github.com:s3720974/Unix2.git
git clone --depth=1 https://github.com/raspberrypi/linux

# Move files from git to directory of build_kernel script
cd Unix2
mv .config ..
mv performance_monitor1 ..

# Creates a default configuration file
cd linux
make $defconfig
cd ..

# Moves config file downloaded from github to kernel installation folder
mv .config linux
cd linux

# Backs up boot files
sudo tar -cvf backup.tar /boot/

# Compilation and Building of Kernel + Copying of important files to boot folder
cd linux
make -j4 zImage modules dtbs
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img

# Terminates performance_monitor1 script
pkill -f performance_monitor1

# Reboot Pi
sudo reboot