#!/bin/bash
#Kernel Compilation

case EXPRESSION in

  PATTERN_1)
KERNEL=kernel7l
make bcm2711_defconfig
    ;;


  PATTERN_2)
KERNEL=kernel7
make bcm2709_defconfig
    ;;

  PATTERN_N)
    STATEMENTS
    ;;

  *)
    STATEMENTS
    ;;
esac